name: Brainrot CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "Makefile"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "Makefile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc flex bison libfl-dev -y

      - name: Build Brainrot
        run: |
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: brainrot
          path: brainrot

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Brainrot artifact
        uses: actions/download-artifact@v4
        with:
          name: brainrot

      - name: Grant execute permissions to Brainrot
        run: chmod +x brainrot

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip valgrind -y
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        working-directory: tests

      - name: Run Pytest
        run: |
          source .venv/bin/activate
          pytest -v test_brainrot.py
        working-directory: tests

      - name: Run Valgrind on all .brainrot tests
        run: |
          chmod +x run_valgrind_tests.sh
          ./run_valgrind_tests.sh
        working-directory: .
